<?php

/** @var $block \Magento\Framework\View\Element\Template */
/** @var \Perspective\GetCurrentProduct\ViewModel\GetCurrentProduct $viewModel */

$viewModel = $block->getData('view_model');

if ($currentProduct = $viewModel->getCurrentProduct()) {
    echo __('Product name: ') . '<a href="' . $currentProduct->getProductUrl() . '">' . $currentProduct->getName() . '</a><br />';
    echo __('Product SKU: ') . $currentProduct->getSku() . '<br />';
    echo __('Product price: ') . $currentProduct->getFinalPrice() . '<br />';
    echo __('Product Category Ids: ');
    print_r ($currentProduct->getCategoryIds()) . '<br />';
}

/** @var \Magento\Catalog\Api\Data\CategoryInterface|null $currentCategory */

if ($currentCategory = $viewModel->getCategory()) {
    echo '<br />' . __('Category name: ') . '<a href="' . $currentCategory->getUrl() . '">' . $currentCategory->getName() . '</a><br />';
}
